In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size=10000

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[6543, 3291, 5689, 1653],
 [6543, 3291, 5689, 8098],
 [6543, 6456, 5689, 5819],
 [1140, 5199, 80, 1208, 1739],
 [1140, 5199, 80, 1208, 6063],
 [7792, 6543, 3594, 5689, 82],
 [4149, 6746, 9488, 1208]]

In [7]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [26]:
import numpy as np

In [11]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 6543 3291 5689 1653]
 [   0    0    0    0 6543 3291 5689 8098]
 [   0    0    0    0 6543 6456 5689 5819]
 [   0    0    0 1140 5199   80 1208 1739]
 [   0    0    0 1140 5199   80 1208 6063]
 [   0    0    0 7792 6543 3594 5689   82]
 [   0    0    0    0 4149 6746 9488 1208]]


In [12]:
## feature representation
dim=10

In [13]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

c:\Users\srbha\OneDrive\Desktop\New folder\WORD EMBEDDINGS PROJECT\.venv\lib\site-packages\keras\src\layers\core\embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [17]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [14]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 532ms/step


array([[[-0.03598373, -0.02670221, -0.04705187, -0.01103394,
         -0.03215239,  0.04773759, -0.03667513, -0.02278316,
          0.01318898, -0.00781689],
        [-0.03598373, -0.02670221, -0.04705187, -0.01103394,
         -0.03215239,  0.04773759, -0.03667513, -0.02278316,
          0.01318898, -0.00781689],
        [-0.03598373, -0.02670221, -0.04705187, -0.01103394,
         -0.03215239,  0.04773759, -0.03667513, -0.02278316,
          0.01318898, -0.00781689],
        [-0.03598373, -0.02670221, -0.04705187, -0.01103394,
         -0.03215239,  0.04773759, -0.03667513, -0.02278316,
          0.01318898, -0.00781689],
        [ 0.00464882, -0.00221388,  0.02070956, -0.02292124,
         -0.03418721, -0.00800528, -0.03575569,  0.04583392,
          0.01746353, -0.0281881 ],
        [ 0.01189781,  0.04483649, -0.00544991, -0.0477309 ,
         -0.00408246,  0.01758469,  0.00983399, -0.00632955,
         -0.00201609, -0.0028053 ],
        [ 0.04422149,  0.02711404, -0.0065151 ,  0.0

In [29]:
import numpy as np
model.predict(np.array([embedded_docs[0]]))


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step


array([[[-0.03598373, -0.02670221, -0.04705187, -0.01103394,
         -0.03215239,  0.04773759, -0.03667513, -0.02278316,
          0.01318898, -0.00781689],
        [-0.03598373, -0.02670221, -0.04705187, -0.01103394,
         -0.03215239,  0.04773759, -0.03667513, -0.02278316,
          0.01318898, -0.00781689],
        [-0.03598373, -0.02670221, -0.04705187, -0.01103394,
         -0.03215239,  0.04773759, -0.03667513, -0.02278316,
          0.01318898, -0.00781689],
        [-0.03598373, -0.02670221, -0.04705187, -0.01103394,
         -0.03215239,  0.04773759, -0.03667513, -0.02278316,
          0.01318898, -0.00781689],
        [ 0.00464882, -0.00221388,  0.02070956, -0.02292124,
         -0.03418721, -0.00800528, -0.03575569,  0.04583392,
          0.01746353, -0.0281881 ],
        [ 0.01189781,  0.04483649, -0.00544991, -0.0477309 ,
         -0.00408246,  0.01758469,  0.00983399, -0.00632955,
         -0.00201609, -0.0028053 ],
        [ 0.04422149,  0.02711404, -0.0065151 ,  0.0